# Site settings
title: 'Commit-Confirm'
description: 'This site is a personal project mainly intended as a repository of somewhat limited knowledge. I aim to use it as a tool to aid in committing topics of interest to my typically poor memory. - Lee Dowdells'
url: 'https://commit-confirm.github.io'
baseurl: ''
google_analytics: 'UA-123062478-1'
disqus_shortname: 'commit-confirm-github-io'

author:
  name: 'Lee Dowdells'
  email: lee-2098@live.co.uk
  twitter_username: 'commit_confirm'
  facebook_username: '@commit-confirm'
  github_username:  'commit-confirm'
  linkedin_username:  'lee-dowdells-2a4853b6'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
