# Site settings
title: The Dumping Blog
description: 'I will be dumping content to this page and refining it later. Also still to program the redirect the social media buttons below correctly - Lee Dowdells'
url: 'https://lee2098.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Lee Dowdells'
  email: lee-2098@live.co.uk
  twitter_username: 'commit_confirm'
  facebook_username: '@commit-confirm'
  github_username:  404
  linkedin_username:  404

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
