baseurl = 'https://www.leegacysystem.dev/'
languageCode = 'en-us'
title = 'Leegacy System'
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

publishDir = "docs" # Required for Github pages

[params]
    author = "Lee Dowdells"
    description = "A personal stash of notes covering various topics"
    keywords = "blog, devops, neteng, juniper"
    info = "Cloud & DevOps Specialist"
    avatarurl = "images/ny_jetSki2.jpg"
    since = 2018

    faviconSVG = "/images/site/favicon.svg"
    favicon_32 = "/images/site/favicon-32x32.png"
    favicon_16 = "/images/site/favicon-16x16.png"

    enableTwemoji = true
    colorScheme = "dark"
    hidecolorschemetoggle = false
    rtl = false

    # Series see also post count
    maxSeeAlsoItems = 20

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/app.js", "js/particles.js"]
  customHomeJS = ["js/particles.js", "js/app.js"]

[languages]
    [languages.en]
        languagename = "English"
        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
	name = "Email"
	icon = "far fa-envelope"
	weight = 0
  url = "mailto:LeegacySystem@outlook.com"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/LeegacySystem"

[[params.social]]
	name = "LinkedIn"
	icon = "fab fa-linkedin"
	weight = 2
	url = "https://www.linkedin.com/in/lee-dow180/"

[params.cloudflare]
    token = "a3e23d0e9f3541179b1ae8f47639e993"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Required to generate links to image
